export const SET_COMPILATION_EMAILS = 'SET_COMPILATION_EMAILS';

export const SET_PROPERTY_FOR_FILTERED_ACCOUNT_EMAIL = 'SET_SELECTED_FOR_FILTERED_ACCOUNT_EMAIL';
export const SET_PROPERTY_FOR_ALL_FILTERED_ACCOUNT_EMAILS = 'SET_SELECTED_FOR_ALL_FILTERED_ACCOUNT_EMAILS';

export const SET_PREVIEW_EMAIL_HASH_ID = 'SET_PREVIEW_EMAIL_HASH_ID';

export const ADD_FILTERED_ACCOUNT_EMAIL = 'ADD_FILTERED_ACCOUNT_EMAIL';
export const SET_FILTERED_ACCOUNT_EMAILS = 'SET_FILTERED_ACCOUNT_EMAILS';

export const SET_FILTERED_ACCOUNT_EMAILS_COUNT = 'SET_FILTERED_ACCOUNT_EMAILS_COUNT';
export const SET_FETCHING_FILTERED_ACCOUNT_EMAILS_COUNT = 'SET_FETCHING_FILTERED_ACCOUNT_EMAILS_COUNT';

export const SET_FETCHING_FILTERED_ACCOUNT_EMAILS = 'SET_FETCHING_FILTERED_ACCOUNT_EMAILS';

export const ADD_COMPILATION = 'ADD_COMPILATION';
export const SET_COMPILATIONS = 'SET_COMPILATIONS';

export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const UPDATE_ACCOUNT_IN_ACCOUNTS = 'UPDATE_ACCOUNT_IN_ACCOUNTS';

export const SET_SELECTED_ACCOUNT_ID = 'SET_SELECTED_ACCOUNT_ID';

export const SET_USER = 'SET_USER';
export const GET_USER = 'GET_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_USER_ERRORS = 'SET_USER_ERRORS';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const ADD_POST = 'ADD_POST';
export const CHANGE_SELECTED_POST = 'CHANGE_SELECTED_POST';
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POSTS = 'ADD_POSTS';
export const ADD_SELECTED_POST = 'ADD_SELECTED_POST';
export const DELETE_POST = 'DELETE_POST';
