export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';

export const SET_SELECTED_ACCOUNT = 'SET_SELECTED_ACCOUNT';
export const SET_EDITING_ACCOUNT = 'SET_EDITING_ACCOUNT';

export const SET_USER = 'SET_USER';
export const GET_USER = 'GET_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_USER_ERRORS = 'SET_USER_ERRORS';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const ADD_POST = 'ADD_POST';
export const CHANGE_SELECTED_POST = 'CHANGE_SELECTED_POST';
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POSTS = 'ADD_POSTS';
export const ADD_SELECTED_POST = 'ADD_SELECTED_POST';
export const DELETE_POST = 'DELETE_POST';
