export const SET_PROPERTY_FOR_COMPILATION_PAGE = 'SET_PROPERTY_FOR_COMPILATION_PAGE';
export const UPDATE_PAGE_IN_COMPILATION_PAGES = 'UPDATE_PAGE_IN_COMPILATION_PAGES';

export const SET_PROPERTY_FOR_COMPILATION_EMAIL = 'SET_PROPERTY_FOR_COMPILATION_EMAIL';
export const UPDATE_EMAIL_IN_COMPILATION_EMAILS = 'UPDATE_EMAIL_IN_COMPILATION_EMAILS';

export const SET_PROPERTY_FOR_FILTERED_ACCOUNT_EMAIL = 'SET_SELECTED_FOR_FILTERED_ACCOUNT_EMAIL';
export const SET_PROPERTY_FOR_ALL_FILTERED_ACCOUNT_EMAILS = 'SET_SELECTED_FOR_ALL_FILTERED_ACCOUNT_EMAILS';
export const SET_PROPERTY_FOR_SOME_FILTERED_ACCOUNT_EMAILS = 'SET_PROPERTY_FOR_SOME_FILTERED_ACCOUNT_EMAILS';

export const SET_CURRENT_FILTERED_EMAIL_MID = 'SET_CURRENT_FILTERED_EMAIL_MID';
export const SET_CURRENT_COMPILATION_EMAIL_ID = 'SET_CURRENT_COMPILATION_EMAIL_ID';

export const SET_EDITING_CURRENT_COMPILATION_EMAIL = 'SET_EDITING_CURRENT_COMPILATION_EMAIL';

export const ADD_FILTERED_ACCOUNT_EMAIL = 'ADD_FILTERED_ACCOUNT_EMAIL';
export const SET_FILTERED_ACCOUNT_EMAILS = 'SET_FILTERED_ACCOUNT_EMAILS';

export const SET_FILTERED_ACCOUNT_EMAILS_COUNT = 'SET_FILTERED_ACCOUNT_EMAILS_COUNT';
export const SET_FETCHING_FILTERED_ACCOUNT_EMAILS_COUNT = 'SET_FETCHING_FILTERED_ACCOUNT_EMAILS_COUNT';

export const SET_FETCHING_FILTERED_ACCOUNT_EMAILS = 'SET_FETCHING_FILTERED_ACCOUNT_EMAILS';

export const ADD_COMPILATION = 'ADD_COMPILATION';
export const UPDATE_COMPILATION_IN_COMPILATIONS = 'UPDATE_COMPILATION_IN_COMPILATIONS';
export const SET_PROPERTY_FOR_COMPILATION = 'SET_PROPERTY_FOR_COMPILATION';
export const SET_COMPILATIONS = 'SET_COMPILATIONS';
export const SET_COMPILATION_EMAILS = 'SET_COMPILATION_EMAILS';
export const SET_COMPILATION_PAGES = 'SET_COMPILATION_PAGES';
export const ADD_COMPILATION_EMAIL = 'ADD_COMPILATION_EMAIL';
export const REMOVE_COMPILATION_EMAIL = 'REMOVE_COMPILATION_EMAIL';

export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const UPDATE_ACCOUNT_IN_ACCOUNTS = 'UPDATE_ACCOUNT_IN_ACCOUNTS';

export const SET_CURRENT_ACCOUNT_ID = 'SET_CURRENT_ACCOUNT_ID';
export const SET_COMPILATION_EMAIL_PAGE_MAP = 'SET_COMPILATION_EMAIL_PAGE_MAP';

export const SET_USER = 'SET_USER';
export const GET_USER = 'GET_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_USER_ERRORS = 'SET_USER_ERRORS';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const ADD_POST = 'ADD_POST';
export const CHANGE_SELECTED_POST = 'CHANGE_SELECTED_POST';
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POSTS = 'ADD_POSTS';
export const ADD_SELECTED_POST = 'ADD_SELECTED_POST';
export const DELETE_POST = 'DELETE_POST';
