export const SET_COMPILATIONS = 'SET_COMPILATIONS';
export const SET_USERS = 'SET_USERS';
export const SET_ORDERS = 'SET_ORDERS';
export const SET_PURCHASE_ORDERS = 'SET_PURCHASE_ORDERS';
export const ADD_PURCHASE_ORDER = 'ADD_PURCHASE_ORDER';
export const REMOVE_PURCHASE_ORDER = 'REMOVE_PURCHASE_ORDER';
export const UPDATE_PURCHASE_ORDER_IN_PURCHASE_ORDERS = 'UPDATE_PURCHASE_ORDER_IN_PURCHASE_ORDERS';

export const SET_USER = 'SET_USER';
export const SET_USER_ERRORS = 'SET_USER_ERRORS';
export const SET_PROPERTY_FOR_USER = 'SET_PROPERTY_FOR_USER';
export const RESET_STATE = 'RESET_STATE';

export const UPDATE_COMPILATION_IN_COMPILATIONS = 'UPDATE_COMPILATION_IN_COMPILATIONS';
export const APPEND_TO_COMPILATION_LOG = 'APPEND_TO_COMPILATION_LOG';
export const APPEND_TO_COMPILATION_COVER_LOG = 'APPEND_TO_COMPILATION_COVER_LOG';
