export default {
  config: {},
  fetching: {},
  user: {},
  allUsers: [],
  accounts: [],
  addresses: [],
  accountPasswordMap: {},
  compilations: [],
  allCompilations: [],
  compilationEmails: [],
  compilationPages: [],
  compilationEmailPageMap: {},
  compilationPdfLog: [],
  currentAccountId: '',
  filteredAccountEmails: [],
  currentFilteredEmailMid: '',
  cart: {},
  checkout: {},
};
