export default {
  config: {},
  fetching: {},
  user: {},
  accounts: [],
  addresses: [],
  accountPasswordMap: {},
  compilations: [],
  compilationEmails: [],
  compilationPages: [],
  filteredAccountEmails: [],
  filteredAccountEmailsResults: {},
  currentFilteredAccountEmail: {},
  selectedFilteredEmailIds: [],
  currentFilteredEmailMid: '',
  cart: {},
  checkout: {},
  orders: [],
};
